FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    confluent-kafka==2.3.0 \
    psycopg2-binary==2.9.9

COPY ../src/stream_processing /app/stream_processing
COPY ../src/common /app/common

CMD ["python", "-u", "stream_processing/main.py"]
