FROM python:3.11-slim

WORKDIR /app

# Dependencies installieren
RUN pip install --no-cache-dir \
    confluent-kafka==2.3.0 \
    psycopg2-binary==2.9.9

# Code kopieren
COPY ../src/sensor_simulator /app/sensor_simulator
COPY ../src/common /app/common

# Endlosschleife läuft bereits im main.py
CMD ["python", "-u", "sensor_simulator/main.py"]
